### GENERAL SETTINGS ###

# Site settings
title: Emily Vernon
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: "UA-44815610-1"
baseurl: "" #important: start with /
url: "http://emilyvernon.com"

# Build settings
markdown: kramdown
permalink: /blog/:title
# excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is


lsi: false
safe: true
# future: true

colors:  #in hex code if not noted else
  primary: "#7bcab7" #"#F70031"
  primary_rgb: "123,202,183" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#ffffff" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  title_hover: "#ff897f"


collections:
  projects:
    output: true
    permalink: /projects/:path/
    layout: project

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "projects"
      type: "projects"
    values:
      layout: "project"

where: Amsterdam, Netherlands
email: emily@emilyvernon.com
tel: +31 6 52603180
# repository: emilygv/emilyvernon.com

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-sass-converter
  # - jekyll-github-metadata

social:
  - title: linkedin
    url: http://linkedin.com/in/emilygvernon
  - title: facebook
    url: https://www.facebook.com/emilyvernon
  - title: instagram
    url: http://instagram.com/emilygv
  - title: tumblr
    url: http://helloemilyvernon.tumblr.com
  - title: google-plus
    url: https://plus.google.com/104794774790907430650
  - title: rss
    url: http://emilyvernon.com/feed.xml

prose:
  siteurl: "http://emilyvernon.com"
  ignore:
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "img"
        field:
          label: "Image Url"
          element: "text"
          placeholder: "Url of image, Ex: on flickr"
