
title: Emily Vernon
# description: "Guest and consumer experience (CX) consultant in Amsterdam"
baseurl: "" #important: start with /
url: "http://emilyvernon.com"

markdown: kramdown
permalink: /insights/:slug
show_excerpts: true
# excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

lsi: false
safe: true
# remote_theme: chrisrhymes/bulma-clean-theme

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      show_sidebar: false
  # - scope:
  #     path: "projects"
  #     type: "projects"
  #   values:
  #     layout: "project"

# collections:
#   projects:
#     output: true
#     permalink: /projects/:path/
#     layout: project

plugins:
  - jekyll-default-layout
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-avatar
  # - jekyll-github-metadata
  # - jekyll-optional-front-matter

# Plugins config
repository: emilygv/emilyvernon.com

paginate: 12
paginate_path: "/insights/page:num/"

# readme_index:
#   remove_originals: true
#   with_frontmatter: false

# optional_front_matter:
#   remove_originals: true

# sass:
    # sass_dir: ./_scss

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - tmp
  - .vscode

where: Amsterdam, Netherlands
email: emily@emilyvernon.com
tel: +31 6 52603180
  
google:
  analytics: "UA-44815610-1"
  site_verification: "pX_KiU17pqFQSun5Bhfv9ebFvsXRXoA5nMMG_6BeNvw"


social:
  - title: linkedin
    url: http://linkedin.com/in/emilygvernon
  - title: facebook
    url: https://www.facebook.com/emilyvernon
  - title: instagram
    url: http://instagram.com/emilygv
  - title: tumblr
    url: http://helloemilyvernon.tumblr.com
  - title: google-plus
    url: https://plus.google.com/104794774790907430650
  - title: rss
    url: http://emilyvernon.com/feed.xml
