-
  title: Brand Strategy
  description: Establish robust creative directions and positioning.
  points:
    - Comprehensive audits
    - Brand positioning & narrative
    - Creative & commercial vision
    - Ideation workshop

-
  title: Consumer Experience
  description: Create consumer experiences to superseded expectation.
  points:
    - Consumer journey mapping
    - Omni-channel strategy
    - Service design & rituals
    - Experience scalability

-
  title: Content Development
  description: Refine the concept through content and communication.
  points:
    - Content & visual strategy
    - Communication hierarchy
    - Guidelines & documentation
    - Sell-in presentations & scripts
