-
  title: Consumer Experience (CX) Design
  description: The concept of experience is blurry. Together, we can clarify the scope, create a vision and construct a roadmap around engaging customers or guests at the right place and time. Touchpoint definition is approached from both a consumer and brand perspective.
  points:
    - Consumer journey mapping
    - Service design & rituals
    - Omni-channel strategy
    - Experience scalability

-
  title: Brand Strategy
  description: Competition is fierce. By better defining the brand’s purpose, personality and attributes, your brand can differentiate within the market. This also serves as a foundation for business expansion and cross-functional projects. 
  points:
    - Brand positioning & narrative
    - Comprehensive brand audits
    - Creative & commercial vision
    - Ideation workshops

-
  title: Tone of Voice
  description: Brands talk all the time. This happens throughout the consumer journey, whether it’s in-store, in-person, online or through an app. Better defining and implementing the brand’s tone of voice ensures message suitability and consistency.
  points:
    - Tone of voice creation
    - Communication hierarchy
    - Service messaging
    - Guidelines & documentation

-
  title: Project Governance
  description: We've all been there - new stakeholders, corporate hierarchy and siloed teams. Through a number of tools and an informed perspective, I can help facilitate cross-functional communication, partnerships and ideation to ultimately realise your vision.
  points:
    - Cross-functional alignment
    - Stakeholder management
    - Sell-in presentations
    - Presentation coaching