- title: Customer Experience
  description: |-
    The concept of experience is blurry. We can create a vision and roadmap around engaging customers or users. Touchpoint definition is approached from both a customer and brand perspective.
    - Customer journey mapping
    - Service design & rituals
    - Omni-channel strategy
    - Experience scalability

- title: Brand Strategy
  description: |-
    Competition is fierce. By defining the brand’s purpose, personality and attributes, your brand can differentiate within the market. This is the foundation for business expansion and cross-functional projects. 
    - Brand positioning & narrative
    - Comprehensive brand audits
    - Creative & commercial vision
    - Ideation workshops

- title: UX/UI Design
  description: |-
    Digital platforms are key for brands today. By understanding your target user and product USPs, we can identify, ideate and design a desirable, viable interface. This can be a website, application or product display.
    - Research & testing
    - Wireframing & prototyping
    - Visual design
    - Style guides
    

